# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Helio's Blog"
description: "Thoughts, memories, hacker and handmade things"
email: 2@lio.pw
logo: "/assets/images/author.png"
cover: "/assets/images/hammer.png"
name: 'Helio Oliveira'
author: 'Helio Oliveira'
author_image: "/assets/images/author.png"

paginate:	5

url: "http://blog.lio.pw"
baseurl: ""

social:
  - icon:	twitter
    url:	https://twitter.com/heliohead
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: "?text="
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/heliohead
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

gems:
  - jekyll-sitemap

muut_name: heliosblog